### ISSUE TITLE
opx_eth_drv runs constantly with 12-15% CPU while there is no port connected

### ISSUE THREAD

**Issue by disaster123** [open-switch/opx-nas-daemon#37]
I'm not really sure what opx_eth_drv does but it runs with a constant rate of 13% CPU in my dell box while there is no port connected and the switch does no traffic.

Is this expected?

An strace shows that it is constantly reading and writing from file descriptor 15 which is
lrwx------ 1 root root 64 May  7 06:02 15 -> /dev/net/tun

**Comment by hpersh** [comment]
This is a DPDK user-space driver, for the management Ethernet port.

It is deprecated, and will be removed in future OPX releases.

**Comment by disaster123** [comment]
Am 08.05.19 um 20:42 schrieb Howard Persh:
> This is a DPDK user-space driver, for the management Ethernet port.
> 
> It is deprecated, and will be removed in future OPX releases.

oh ok - any plans for 3.2.0 and a release date?

Grewts,
Stefan

**Comment by jeff-yin** [comment]
There are plans for a 3.2.0 release, but the date is TBD. Estimate is within the next couple of months.

**Comment by disaster123** [comment]
This one seems to be fixed - but nobody seems to look into the github issues?

**Comment by jeffyin-dell** [comment]
my bad
